name: task
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  hive_flutter: 1.1.0
  logging: 1.2.0
  flutter_secure_storage: 9.0.0
  uni_links: 0.5.1
  share_plus: 7.2.1
  freezed_annotation: 2.4.1
  connectivity_plus: 5.0.2
  dio: 5.4.0
  dio_smart_retry: 6.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: 2.4.7
  freezed: 2.4.6
  hive_generator: 2.0.1
  json_serializable: 6.7.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

